api/urls.py
from django.urls import include, path
from rest_framework import routers

from api.views import GoodViewSet, CategoryViewSet, AuthorViewSet


router_v1 = routers.DefaultRouter()
router_v1.register('goods', GoodViewSet, basename='good')
router_v1.register('categories', CategoryViewSet, basename='category')
router_v1.register('authors', AuthorViewSet, basename='author')

urlpatterns = [
    path('v1/', include(router_v1.urls)),
]

goods/urls.py
from django.urls import path

from .views import (
    index,
    good_detail,
    goods_of_category,
    goods_of_author,
    CategoryCreateView,
    GoodCreateView,
    AuthorCreateView,
)

app_name = 'goods'

urlpatterns = [
    path('category/create/', CategoryCreateView.as_view(), name='category_create'),
    path('good/create/', GoodCreateView.as_view(), name='good_create'),
    path('author/create/', AuthorCreateView.as_view(), name='author_create'),
    path('category/<slug:slug>/', goods_of_category, name='category'),
    path('author/<int:id>/', goods_of_author, name='author'),
    path('<int:id>/', good_detail, name='detail'),
    path('', index, name='index'),

]

store/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls'), name='api'),
    path('', include('goods.urls'), name='goods'),
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView


app_name = 'users'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

goods/models.py
from django.db import models

from .constants import MAX_LENGTH_CHAR_FIELD
from .enums import ProductTypeEnum


class Author(models.Model):
    name = models.CharField('Имя', max_length=MAX_LENGTH_CHAR_FIELD)
    age = models.IntegerField('Возраст')
    country = models.CharField('Страна', max_length=MAX_LENGTH_CHAR_FIELD)

    class Meta:
        verbose_name = 'Автор'
        verbose_name_plural = 'Авторы'

    def __str__(self):
        return self.name


class Category(models.Model):
    title = models.CharField('Название', max_length=MAX_LENGTH_CHAR_FIELD)
    slug = models.SlugField('Слаг', unique=True)
    description = models.TextField('Описание', blank=True)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.title


class Good(models.Model):
    title = models.CharField('Название', max_length=MAX_LENGTH_CHAR_FIELD)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, verbose_name='Автор', related_name='goods')
    categories = models.ManyToManyField(Category, verbose_name='Категории', related_name='goods')
    description = models.TextField('Описание', blank=True)
    product_type = models.CharField(
        'Тип продукта',
        max_length=MAX_LENGTH_CHAR_FIELD,
        choices=ProductTypeEnum.choices(),
    )
    created_at = models.DateTimeField('Дата создания', auto_now_add=True)
    updated_at = models.DateTimeField('Дата обновления', auto_now=True)
    creator = models.ForeignKey('users.User', on_delete=models.CASCADE, verbose_name='Создатель', related_name='goods')

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    def __str__(self):
        return self.title

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    middle_name = models.CharField(max_length=150, blank=True, null=True)
    phone = models.CharField(max_length=150, blank=True, null=True)
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=150, blank=False, null=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'first_name', 'last_name', 'phone']

goods/forms.py
from django.forms import ModelForm

from .models import Good, Category, Author


class AuthorForm(ModelForm):
    class Meta:
        model = Author
        fields = '__all__'


class CategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = '__all__'


class GoodForm(ModelForm):
    class Meta:
        model = Good
        exclude = ('creator',)

api/views.py
from rest_framework import viewsets

from goods.models import Good, Category, Author
from .serializers import GoodReadSerializer, GoodWriteSerializer, CategorySerializer, AuthorSerializer


class GoodViewSet(viewsets.ModelViewSet):

    def get_serializer_class(self):
        if self.action in ['list', 'retrieve']:
            return GoodReadSerializer
        return GoodWriteSerializer

    def get_queryset(self):
        return Good.objects.select_related(
            'author',
        ).prefetch_related(
            'categories',
        ).order_by('author__name', 'id')


class CategoryViewSet(viewsets.ModelViewSet):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer


class AuthorViewSet(viewsets.ModelViewSet):
    queryset = Author.objects.all()
    serializer_class = AuthorSerializer

goods/views.py
import random

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .constants import MAX_OBJECTS_ON_PAGE
from .helpers import query_debugger
from .models import Author, Good, Category
from .forms import GoodForm, CategoryForm, AuthorForm


# @query_debugger
def index(request):
    goods = Good.objects.select_related('author').prefetch_related('categories').order_by('-created_at')[:MAX_OBJECTS_ON_PAGE]
    return render(request, 'goods/index.html', {'goods': goods})


# @query_debugger
def good_detail(request, id):
    good = get_object_or_404(Good.objects.select_related('author').prefetch_related('categories'), pk=id)

    return render(request, 'goods/detail.html', {'good': good})


# @query_debugger
def goods_of_category(request, slug):
    category = get_object_or_404(Category, slug=slug)
    goods = category.goods.select_related('author').prefetch_related('categories')[:MAX_OBJECTS_ON_PAGE]

    return render(request, 'goods/index.html', {'goods': goods})


# @query_debugger
def goods_of_author(request, id):
    author = get_object_or_404(Author, pk=id)
    goods = author.goods.prefetch_related('categories')[:MAX_OBJECTS_ON_PAGE]

    return render(request, 'goods/index.html', {'goods': goods})


class CategoryCreateView(CreateView):
    model = Category
    form_class = CategoryForm
    template_name = 'goods/category_form.html'
    success_url = reverse_lazy('goods:index')


class GoodCreateView(LoginRequiredMixin, CreateView):
    model = Good
    form_class = GoodForm
    template_name = 'goods/good_form.html'
    success_url = reverse_lazy('goods:index')

    def form_valid(self, form):
        form.instance.creator = self.request.user
        return super().form_valid(form)


class AuthorCreateView(CreateView):
    model = Author
    form_class = AuthorForm
    template_name = 'goods/author_form.html'
    success_url = reverse_lazy('goods:index')

users/views.py
from django.shortcuts import render

# Create your views here.

templates/goods/author_form.html
{% extends 'goods/extends/base.html' %}

{% block content %}
    <div class="container">
        <form method="post" action="{% url 'goods:author_create' %}">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Create">
        </form>
    </div>
{% endblock %}

templates/goods/category_form.html
{% extends 'goods/extends/base.html' %}

{% block content %}
    <div class="container">
        <form method="post" action="{% url 'goods:category_create' %}">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Create">
        </form>
    </div>
{% endblock %}

templates/goods/detail.html
{% extends 'goods/extends/base.html' %}

{% block title %}{{ good.title }}{% endblock %}
{% block header %}{{ good.title }}{% endblock %}

{% block content %}
    <div class="container">
        {% include 'goods/includes/good.html' %}
        <a href="{% url 'goods:index' %}">На главную</a>
    </div>
{% endblock %}

templates/goods/extends/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <title>{% block title %}{% endblock %} | Наши фильмы</title>
</head>
<body>
    {% include 'includes/header.html' %}
    <div class="container">
        <div class="row align-content-center">
            {% block content %}

            {% endblock %}
        </div>
    </div>
</body>
</html>

templates/goods/good_form.html
{% extends 'goods/extends/base.html' %}

{% block content %}
    <div class="container">
        <form method="post" action="{% url 'goods:good_create' %}">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Create">
        </form>
    </div>
{% endblock %}

templates/goods/includes/good.html
<article>
    <h2>{{ good.title }}</h2>
    <p>Автор: <a href="{% url 'goods:author' good.author.id %}">{{ good.author.name }}</a></p>
    <p>Категории:
        {% for category in good.categories.all %}
            <a href="{% url 'goods:category' category.slug %}">{{ category.title }}</a>
        {% endfor %}
</article>

templates/goods/index.html
{% extends 'goods/extends/base.html' %}

{% block content %}
    <div class="container">
        {% for good in goods %}
            {% include 'goods/includes/good.html' %}
            <a href="{% url 'goods:detail' good.id %}">Подробнее</a>
        {% endfor %}
    </div>
{% endblock %}

templates/includes/header.html
<header>
    <nav class="d-flex justify-content-between">
        <ul class="list-group list-group-horizontal-sm">
            <li class="list-group-item"><a href="{% url 'goods:index' %}">Главная</a></li>
            <li class="list-group-item"><a href="{% url 'goods:author_create' %}">Создать автора</a></li>
            <li class="list-group-item"><a href="{% url 'goods:category_create' %}">Создать категорию</a></li>
            <li class="list-group-item"><a href="{% url 'goods:good_create' %}">Добавить товар</a></li>
        </ul>
        <ul class="list-group list-group-horizontal-sm">
        {% if user.is_authenticated %}
            <li class="list-group-item">Привет, <a href="">{{ user.first_name }}</a></li>
            <li class="list-group-item">
                <form action="{% url 'users:logout' %}" method="post">
                  {% csrf_token %}
                  <button type="submit">Выйти</button>
                </form>
            </li>
        {% else %}
            <li class="list-group-item"><a href="{% url 'users:login' %}">Войти</a></li>
            <li class="list-group-item"><a href="">Зарегистрироваться</a></li>
        {% endif %}
        </ul>
    </nav>
</header>

templates/users/login.html
{% extends 'goods/extends/base.html' %}

{% block title %}Авторизация{% endblock %}

{% block content %}
    <div class="col-md-6 offset-md-3">
        <h1>Авторизация</h1>
        <form method="post">
            <div class="form-group">
                <label for="email">Почта</label>
                <input type="text" name="username" class="form-control" id="email" placeholder="Почта">
            </div>
            <div class="form-group">
                <label for="password">Пароль</label>
                <input type="password" name="password" class="form-control" id="password" placeholder="Пароль">
            </div>
          {% csrf_token %}
          <button type="submit" class="btn btn-primary">Войти</button>
        </form>
    </div>

{% endblock %}